apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: edge-obs
  labels:
    name: edge-obs
---
apiVersion: v1
kind: Namespace
metadata:
  name: hub-obs
  labels:
    name: hub-obs
---
apiVersion: v1
kind: Namespace
metadata:
  name: testing
  labels:
    name: testing
